CREATE OR REPLACE VDS 
HealthCheck.Application.LoadTestResults 
AS 
SELECT 
	testId as originalTestId,
	CONCAT(LPAD(DENSE_RANK() OVER (ORDER BY testId ASC), 3, '0'), '_E', numExecutors, 'C', numConcurrentUsers, 'Q', numQPU) as testId, 
	testStartTime, 
	jmeterQueryId, 
	testType, 
	numExecutors,
	numConcurrentUsers, 
	numQPU, 
	usersRampTime, 
	userId, 
	queryCounter, 
    TO_TIMESTAMP("start" / 1000.0) as queryStartTime, 
    TO_TIMESTAMP(finish / 1000.0) AS queryFinishTime, 
	totalDurationMS, 
	queryId, 
    SUBSTR(LTRIM(SPLIT_PART(queryText, '|', 10),'counter-'), 
           STRPOS(LTRIM(SPLIT_PART(queryText, '|', 10),'counter-'), 'SELECT')) as queryText, 
	queryChunkSizeBytes, 
	nrQueryChunks, 
	"start" AS "start", 
	finish, 
	outcome, 
	username, 
	requestType, 
	queryType, 
	queueName, 
    poolWaitTime, 
	planningTime, 
	enqueuedTime, 
	executionTime, 
	accelerated, 
	reflectionRelationships, 
	inputRecords, 
	inputBytes, 
	outputRecords, 
	outputBytes, 
	queryCost, 
	dremioHost, 
	testDescription, 
	profileUrl 
FROM HealthCheck.Business.TestQueryData 
ORDER BY testId, "start"